# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=350)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('meta', models.CharField(max_length=900)),
                ('publish', models.BooleanField()),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
