# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=350)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('id_name', models.CharField(max_length=50, unique=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Pages')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Section',
            },
        ),
    ]
