# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
