# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, upload_to='./client-banners/'),
        ),
    ]
