# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_pieces_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieces',
            name='date',
        ),
        migrations.AddField(
            model_name='pieces',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pieces',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
