# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20170502_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='body',
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
